_tuning_objective_metric: '"validation:rmse"'
border_count: '"255"'
depth: '7'
iterations: '178'
l2_leaf_reg: '1.0'
learning_rate: '0.08894101557848919'
min_data_in_leaf: '5'
random_strength: '2.798792221111956'
rsm: '0.8009864414232702'
sagemaker_container_log_level: '20'
sagemaker_estimator_class_name: '"SKLearn"'
sagemaker_estimator_module: '"sagemaker.sklearn.estimator"'
sagemaker_job_name: '"Catboostt-hpo-20260802-213535"'
sagemaker_program: '"train.py"'
sagemaker_region: '"us-east-1"'
sagemaker_submit_directory: '"s3://sagemaker-us-east-1-135053048192/Catboostt-hpo-20260802-213535/source/sourcedir.tar.gz"'
subsample: '0.9164947760169949'
