_tuning_objective_metric: '"validation:rmse"'
colsample_bytree: '0.6430011758233989'
gamma: '1.8851230961121752'
learning_rate: '0.04207928366322871'
max_depth: '10'
min_child_weight: '11'
n_estimators: '198'
reg_alpha: '0.9443197532443477'
reg_lambda: '0.6254392572527134'
sagemaker_container_log_level: '20'
sagemaker_estimator_class_name: '"SKLearn"'
sagemaker_estimator_module: '"sagemaker.sklearn.estimator"'
sagemaker_job_name: '"Xgboost-hpo-20260802-161000"'
sagemaker_program: '"train.py"'
sagemaker_region: '"us-east-1"'
sagemaker_submit_directory: '"s3://sagemaker-us-east-1-135053048192/Xgboost-hpo-20260802-161000/source/sourcedir.tar.gz"'
subsample: '0.920919252701866'
