_tuning_objective_metric: '"validation:rmse"'
colsample_bytree: '0.7590534219739528'
learning_rate: '0.1'
max_depth: '"-1"'
min_child_samples: '15'
min_split_gain: '0.5596071012629376'
n_estimators: '280'
num_leaves: '30'
reg_alpha: '0.3878048899448767'
reg_lambda: '1.8054231471407953'
sagemaker_container_log_level: '20'
sagemaker_estimator_class_name: '"SKLearn"'
sagemaker_estimator_module: '"sagemaker.sklearn.estimator"'
sagemaker_job_name: '"lightgbm-hpo-20260802-131443"'
sagemaker_program: '"train.py"'
sagemaker_region: '"us-east-1"'
sagemaker_submit_directory: '"s3://sagemaker-us-east-1-135053048192/lightgbm-hpo-20260802-131443/source/sourcedir.tar.gz"'
subsample: '0.9697029951046401'
subsample_freq: '1'
